import { useEffect, useState } from 'react';
import { Header } from '../components/layout/Header';
import { DataTable } from '../components/ui/DataTable';
import { KpiCard } from '../components/ui/KpiCard';
import { LoadingState } from '../components/ui/LoadingState';
import { SectionPanel } from '../components/ui/SectionPanel';
import { loadAcquisitionPerson } from '../data/acquisition';
import { formatMoney, formatNumber } from '../lib/formatters';
import { countRows, numberFrom, sumRows } from '../lib/metrics';
import type { AnyRow, DashboardFilters, PersonConfig } from '../types';

export function AcquisitionPersonPage({ filters, person }: { filters: DashboardFilters; person: PersonConfig }) {
  const [data, setData] = useState<Awaited<ReturnType<typeof loadAcquisitionPerson>> | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let alive = true; setLoading(true); loadAcquisitionPerson(filters, person.key).then((next) => alive && setData(next)).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [filters, person.key]);
  if (loading || !data) return <LoadingState />;
  const summary = data.summary.rows[0];
  const deals = data.deals.rows;

  if (person.dealsOnly) {
    return <><Header badge="Acquisition Deals View" title={`Acquisition · ${person.displayName}`} subtitle="Deals-only page: open, won, lost and deal amount visibility. No activity coverage is rendered." /><div className="kpiGrid"><KpiCard title="Open Deals Count" value={formatNumber(sumRows(deals, ['open_deals', 'open_deal_count']))} tone="orange" /><KpiCard title="Open Deals Amount" value={formatMoney(sumRows(deals, ['open_amount', 'open_pipeline_amount']))} tone="orange" /><KpiCard title="Won Deals Count" value={formatNumber(sumRows(deals, ['won_deals', 'won_deal_count']))} tone="green" /><KpiCard title="Won Deals Amount" value={formatMoney(sumRows(deals, ['won_amount']))} tone="green" /><KpiCard title="Lost Deals Count" value={formatNumber(sumRows(deals, ['lost_deals', 'lost_deal_count']))} tone="red" /><KpiCard title="Lost Deals Amount" value={formatMoney(sumRows(deals, ['lost_amount']))} tone="red" /></div><SectionPanel title="Open / Won / Lost Deals"><DataTable rows={deals} columns={[{ key: 'deal_name', label: 'Deal' }, { key: 'company_name', label: 'Company' }, { key: 'deal_status', label: 'Status' }, { key: 'stage', label: 'Stage' }, { key: 'amount', label: 'Amount', render: (row: AnyRow) => formatMoney(row.amount) }, { key: 'next_activity_date', label: 'Next Activity' }]} /></SectionPanel><SectionPanel title="Deals at Risk"><DataTable rows={data.dealsAtRisk.rows} columns={[{ key: 'deal_name', label: 'Deal' }, { key: 'company_name', label: 'Company' }, { key: 'amount', label: 'Amount', render: (row: AnyRow) => formatMoney(row.amount) }, { key: 'risk_reason', label: 'Risk Reason' }]} /></SectionPanel></>;
  }

  return <><Header badge="Acquisition Person" title={`Acquisition · ${person.displayName}`} subtitle="Personal command center for Rank A/B coverage, quality touches, financial performance and open deals." /><div className="kpiGrid"><KpiCard title="Assigned Companies" value={formatNumber(numberFrom(summary, ['assigned_companies', 'companies']))} tone="blue" /><KpiCard title="Rank A Companies" value={formatNumber(numberFrom(summary, ['rank_a_companies']))} tone="green" /><KpiCard title="Rank B Companies" value={formatNumber(numberFrom(summary, ['rank_b_companies']))} tone="green" /><KpiCard title="Open Deals" value={formatNumber(sumRows(deals, ['open_deals', 'open_deal_count']))} tone="orange" /><KpiCard title="Connected Calls" value={formatNumber(numberFrom(summary, ['connected_calls']))} tone="blue" /><KpiCard title="Completed Meetings" value={formatNumber(numberFrom(summary, ['completed_meetings']))} tone="blue" /><KpiCard title="Booked This Year" value={formatMoney(sumRows(data.financialSummary.rows, ['booked_this_year', 'booking_amount']))} tone="green" /><KpiCard title="Cashed This Year" value={formatMoney(sumRows(data.financialSummary.rows, ['cashed_this_year', 'cashing_amount']))} tone="blue" /></div><div className="panelGrid"><SectionPanel title="Correct Company Rank Coverage"><DataTable rows={data.rankCoverage.rows} columns={[{ key: 'company_name', label: 'Company' }, { key: 'country', label: 'Country' }, { key: 'rank', label: 'Rank' }, { key: 'touch_status', label: 'Touch Status' }, { key: 'connected_calls', label: 'Connected Calls' }, { key: 'completed_meetings', label: 'Completed Meetings' }, { key: 'next_activity_date', label: 'Next Activity' }]} /></SectionPanel><SectionPanel title="Person Deals at Risk"><DataTable rows={data.dealsAtRisk.rows} columns={[{ key: 'deal_name', label: 'Deal' }, { key: 'company_name', label: 'Company' }, { key: 'stage', label: 'Stage' }, { key: 'amount', label: 'Amount', render: (row: AnyRow) => formatMoney(row.amount) }, { key: 'risk_reason', label: 'Risk Reason' }]} /></SectionPanel><SectionPanel title="Activity Details"><DataTable rows={data.activityDetails.rows} columns={[{ key: 'activity_type', label: 'Type' }, { key: 'company_name', label: 'Company / Account' }, { key: 'owner_name', label: 'Owner' }, { key: 'activity_date', label: 'Date' }, { key: 'outcome', label: 'Outcome' }, { key: 'connected', label: 'Connected' }, { key: 'completed', label: 'Completed' }]} /></SectionPanel></div></>;
}
