import { useEffect, useState } from 'react';
import { Header } from '../components/layout/Header';
import { DataTable } from '../components/ui/DataTable';
import { KpiCard } from '../components/ui/KpiCard';
import { LoadingState } from '../components/ui/LoadingState';
import { SectionPanel } from '../components/ui/SectionPanel';
import { loadRetentionOverview } from '../data/retention';
import { formatMoney, formatNumber, formatPercent } from '../lib/formatters';
import { countRows, sumRows } from '../lib/metrics';
import type { AnyRow, DashboardFilters } from '../types';

export function RetentionOverview({ filters }: { filters: DashboardFilters }) {
  const [data, setData] = useState<Awaited<ReturnType<typeof loadRetentionOverview>> | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let alive = true; setLoading(true); loadRetentionOverview(filters).then((next) => alive && setData(next)).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [filters]);
  if (loading || !data) return <LoadingState />;
  return <><Header badge="Retention" title="Retention Command Center" subtitle="RM and CSM account coverage, tier health, financials, next activity and stale accounts." /><div className="kpiGrid"><KpiCard title="Applicable Accounts" value={formatNumber(countRows(data.personAccounts.rows))} tone="blue" /><KpiCard title="No Next Activity" value={formatNumber(countRows(data.noNextActivity.rows.filter((row) => row.no_next_activity === true)))} tone="orange" /><KpiCard title="Stale Accounts" value={formatNumber(countRows(data.noNextActivity.rows.filter((row) => row.is_stale_21d === true)))} tone="red" /><KpiCard title="Remaining Collection" value={formatMoney(sumRows(data.financialSummary.rows, ['remaining_amount', 'remaining_collection']))} tone="orange" /><KpiCard title="Budget This Year" value={formatMoney(sumRows(data.financialSummary.rows, ['budget_amount', 'budget_this_year']))} tone="blue" /><KpiCard title="Booked This Year" value={formatMoney(sumRows(data.financialSummary.rows, ['booked_amount', 'booked_this_year']))} tone="green" /><KpiCard title="Collected This Year" value={formatMoney(sumRows(data.financialSummary.rows, ['collected_amount', 'cashed_this_year']))} tone="green" /><KpiCard title="Collection Rate" value={formatPercent(sumRows(data.financialSummary.rows, ['collection_rate']))} tone="green" /></div><div className="panelGrid"><SectionPanel title="RM Coverage"><DataTable rows={data.roleCoverage.rows.filter((row) => row.role_type === 'RM')} columns={[{ key: 'person_name', label: 'RM' }, { key: 'accounts', label: 'Accounts' }, { key: 'touched', label: 'Touched' }, { key: 'untouched', label: 'Untouched' }, { key: 'connected_calls', label: 'Connected Calls' }, { key: 'completed_meetings', label: 'Completed Meetings' }, { key: 'remaining_collection', label: 'Remaining', render: (row: AnyRow) => formatMoney(row.remaining_collection) }]} /></SectionPanel><SectionPanel title="CSM Coverage"><DataTable rows={data.roleCoverage.rows.filter((row) => row.role_type === 'CSM')} columns={[{ key: 'person_name', label: 'CSM' }, { key: 'accounts', label: 'Accounts' }, { key: 'tier_a', label: 'Tier A' }, { key: 'tier_b', label: 'Tier B' }, { key: 'tier_c', label: 'Tier C' }, { key: 'empty_tier', label: 'Empty' }, { key: 'remaining_collection', label: 'Remaining', render: (row: AnyRow) => formatMoney(row.remaining_collection) }]} /></SectionPanel><SectionPanel title="Retention No Next Activity"><DataTable rows={data.noNextActivity.rows.filter((row) => row.no_next_activity === true)} columns={[{ key: 'account_name', label: 'Account' }, { key: 'person_name', label: 'Person' }, { key: 'role_type', label: 'Role' }, { key: 'tier', label: 'Tier' }, { key: 'product', label: 'Product' }, { key: 'remaining_amount', label: 'Remaining', render: (row: AnyRow) => formatMoney(row.remaining_amount) }, { key: 'next_activity_date', label: 'Next Activity' }]} /></SectionPanel></div></>;
}
